---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managemeals
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: managemeals
  project: workloads
  source:
    repoURL: https://github.com/mocdaniel/homelab.git
    path: gitops/manifests/workloads/managemeals
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
