---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-civo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync second
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: infrastructure
  source:
    chart: cert-manager-webhook-civo
    repoURL: ghcr.io/okteto
    targetRevision: 0.5.4
    helm:
      values: |
        image:
          repository: okteto/civo-webhook
          tag: 0.5.4
        region: FRA1
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
