---
title: My dashboard
background:
  image: https://images.unsplash.com/photo-1513407030348-c983a97b98d8?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm
  opacity: 50
cardBlur: md
statusStyle: dot
layout:
  Infrastructure:
    style: row
    columns: 4
  Finances:
    style: col
