---
- openmeteo:
    label: Erlangen
    latitude: 49.583332
    longitude: 11.016667
    timezone: Europe/Berlin
    units: metric
    cache: 5
- search:
    provider: google
    focus: true
- resources:
    cpu: true
    memory: true
    disk: /
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: long
    locale: de
