---
version: "3.9"
services:
  ghostfolio:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghostfolio.rule=Host(`ghostfolio.bodkys.house`)"
      - "traefik.http.routers.ghostfolio.entrypoints=websecure"
      - "traefik.http.routers.ghostfolio.tls=true"
      - "traefik.http.routers.ghostfolio.tls.certresolver=letsencrypt"
      - wud.tag.include=^\d+\.\d+\.\d+$$
    image: ghostfolio/ghostfolio:2.61.1
    container_name: ghostfolio
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ghostfolio?connect_timeout=300&sslmode=prefer
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3333/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - traefik
      - ghostfolio

  postgres:
    labels:
      - wud.tag.include=^\d+\.\d+(\.\d+)?$$
    image: postgres:15.5
    environment:
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ghostfolio-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - ghostfolio

  redis:
    labels:
      - wud.tag.include=^alpine\d+\.\d+(\.\d+)?$$
    image: redis:alpine3.19
    command: ["redis-server", "--requirepass", $REDIS_PASSWORD]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ghostfolio-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --pass $REDIS_PASSWORD ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ghostfolio

volumes:
  postgres:

networks:
  ghostfolio: {}
  traefik:
    external: true
