---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe
spec:
  restartPolicy: Never
  nodeName:
  containers:
    - name: disk-wipe
      image: busybox
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c", "blkdiscard /dev/nvme0n1"]
