---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-1
spec:
  restartPolicy: Never
  nodeName: turing-1
  containers:
    - name: disk-wipe
      image: busybox
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c", "blkdiscard /dev/nvme0n1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-2
spec:
  restartPolicy: Never
  nodeName: turing-2
  containers:
    - name: disk-wipe
      image: busybox
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c", "blkdiscard /dev/nvme0n1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-3
spec:
  restartPolicy: Never
  nodeName: turing-3
  containers:
    - name: disk-wipe
      image: busybox
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c", "blkdiscard /dev/nvme0n1"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-4
spec:
  restartPolicy: Never
  nodeName: turing-4
  containers:
    - name: disk-wipe
      image: busybox
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c", "blkdiscard /dev/nvme0n1"]
