---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
  name: repo-argo
  namespace: argocd
stringData:
  name: Argo
  project: argocd
  type: helm
  url: https://argoproj.github.io/argo-helm
