---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  labels:
    app.kubernetes.io/name: semaphore
  annotations:
    argocd.argoproj.io/sync-wave: "3" # sync third
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: semaphore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: semaphore
    spec:
      containers:
        - name: semaphore
          image: semaphoreui/semaphore:v2.9.64
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: SEMAPHORE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-semaphore-app
                  key: username
            - name: SEMAPHORE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-semaphore-app
                  key: password
            - name: SEMAPHORE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-semaphore-app
                  key: host
            - name: SEMAPHORE_DB_PORT
              value: "5432"
            - name: SEMAPHORE_DB_DIALECT
              value: postgres
            - name: SEMAPHORE_DB
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-semaphore-app
                  key: dbname
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/semaphore
            - name: SEMAPHORE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: semaphore-credentials
                  key: password
            - name: SEMAPHORE_ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: semaphore-credentials
                  key: name
            - name: SEMAPHORE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: semaphore-credentials
                  key: email
            - name: SEMAPHORE_ADMIN
              valueFrom:
                secretKeyRef:
                  name: semaphore-credentials
                  key: username
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              valueFrom:
                secretKeyRef:
                  name: semaphore-credentials
                  key: accesskey
