---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: semaphore-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: semaphore-credentials
  data:
    - secretKey: username
      remoteRef:
        key: SEMAPHORE_ADMIN
    - secretKey: name
      remoteRef:
        key: SEMAPHORE_ADMIN_NAME
    - secretKey: password
      remoteRef:
        key: SEMAPHORE_ADMIN_PASSWORD
    - secretKey: email
      remoteRef:
        key: SEMAPHORE_ADMIN_EMAIL
    - secretKey: accesskey
      remoteRef:
        key: SEMAPHORE_ACCESS_KEY_ENCRYPTION
