---
apiVersion: v1
kind: Service
metadata:
  name: actual
  labels:
    app.kubernetes.io/name: actual
spec:
  type: ClusterIP
  ports:
    - port: 5006
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: actual
