---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: k8s-backup
  namespace: velero
spec:
  schedule: 0 1 * * *
  template:
    includeClusterResources: true
  useOwnerReferencesInBackup: true
