---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: rook-ceph
  project: infrastructure
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.13.5
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
