---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  labels:
    app.kubernetes.io/name: linkwarden
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: linkwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:v2.5.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: linkwarden-data
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-linkwarden-app
                  key: uri
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden-credentials
                  key: nextauth_secret
            - name: NEXT_PUBLIC_AUTHENTIK_ENABLED
              value: "true"
            - name: AUTHENTIK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: linkwarden-credentials
                  key: nextauth_client_id
            - name: AUTHENTIK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden-credentials
                  key: nextauth_client_secret
            - name: AUTHENTIK_ISSUER
              value: https://id.bodkys.house/application/o/linkwarden
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              memory: 500Mi
      volumes:
        - name: linkwarden-data
          persistentVolumeClaim:
            claimName: linkwarden-data
