---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
  labels:
    app.kubernetes.io/name: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
