---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  labels:
    app.kubernetes.io/name: actual
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: actual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actual
    spec:
      containers:
        - name: actual
          image: actualbudget/actual-server:edge@sha256:ab9b1b3c445342c269c5944219ef243ecaf0bf1286a97c97a1ebd42470411bd3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: actual-data
      volumes:
        - name: actual-data
          persistentVolumeClaim:
            claimName: actual-data
