---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  commonName: "argocd.bodkys.house"
  dnsNames:
    - "argocd.bodkys.house"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: bodkys-house-wildcard
