---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bodkys-house-wildcard
  namespace: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  commonName: "*.bodkys.house"
  dnsNames:
    - "*.bodkys.house"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: bodkys-house-wildcard
