apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-civo-binding
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
subjects:
  - kind: ServiceAccount
    name: cert-manager # Name is case sensitive
    namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: civo-creator
  apiGroup: rbac.authorization.k8s.io
