---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: semaphore
  project: apps
  source:
    repoURL: https://github.com/mocdaniel/homelab.git
    path: gitops/workloads/manifests/semaphore
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
