---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civo-token
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: civo-token
  data:
    - secretKey: token
      remoteRef:
        key: CIVO_TOKEN
