---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: infrastructure
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
