---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  labels:
    app.kubernetes.io/name: actual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
