- name: Install Docker CE
  hosts: docker
  become: true
  tags: ["docker"]
  vars:
    docker_install_compose_plugin: true
    docker_apt_ignore_key_error: false
    docker_daemon_options:
      metrics-addr: "{{ docker_metrics_endpoint }}"
  roles:
    - role: geerlingguy.docker
