---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-bodkys-house
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # sync third
spec:
  commonName: "argocd.bodkys.house"
  dnsNames:
    - "argocd.bodkys.house"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: argocd-server-tls
