---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghostfolio
  labels:
    app.kubernetes.io/name: ghostfolio
spec:
  rules:
    - host: "ghostfolio.bodkys.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ghostfolio
                port:
                  name: http
  tls:
    - hosts:
        - "ghostfolio.bodkys.house"
