---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghostfolio
  labels:
    app.kubernetes.io/name: ghostfolio
  annotations:
    gethomepage.dev/description: One app to track them all
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Finances
    gethomepage.dev/icon: ghostfolio.png
    gethomepage.dev/name: Ghostfolio
    gethomepage.dev/widget.type: ghostfolio
    gethomepage.dev/widget.url: ghostfolio.ghostfolio.svc
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GHOSTFOLIO_TOKEN}}"
spec:
  rules:
    - host: "ghostfolio.bodkys.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ghostfolio
                port:
                  name: http
  tls:
    - hosts:
        - "ghostfolio.bodkys.house"
