---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio-redis
  labels:
    app.kubernetes.io/name: ghostfolio-redis
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync second
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ghostfolio-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghostfolio-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine3.19
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: redis-password
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
