kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-argocd
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
  - host: argocd.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port: 
                number: 80
