---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civo-s3-credentials
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: civo-s3-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
