---
version: "3.9"

services:
  homepage:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.bodkys.house`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - wud.tag.include=^v\d+\.\d+\.\d+$$
    image: ghcr.io/gethomepage/homepage:v0.8.7
    container_name: homepage
    environment:
      HOMEPAGE_VAR_PORTAINER_TOKEN: ${HOMEPAGE_VAR_PORTAINER_TOKEN}
      HOMEPAGE_VAR_TRAEFIK_PASSWORD: ${HOMEPAGE_VAR_TRAEFIK_PASSWORD}
      HOMEPAGE_VAR_GHOSTFOLIO_TOKEN: ${HOMEPAGE_VAR_GHOSTFOLIO_TOKEN}
    volumes:
      - ./config:/app/config  # this only works with Portainer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
