---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-bootstrap
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/infra
    repoURL: https://github.com/mocdaniel/homelab
    targetRevision: HEAD
    helm:
      parameters:
        - name: domain
          value: {{ .Values.domain }}
        - name: metallb.addresspool
          value: {{ .Values.metallb.addresspool }}
  annotations:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
