---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: v0.13.9
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
