---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync first
spec:
  destination:
    name: in-cluster
    namespace: cnpg-system
  project: infrastructure
  source:
    chart: cluster
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.0.2
    helm:
      values: |
        cluster:
          storage:
            size: 16Gi
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
