---
global:
  external_labels:
    prom_instance: dbodky-staff1

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - 10.77.13.135:9323
          - 10.77.13.135:9323

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
