---
global:
  external_labels:
    prom_instance: dbodky-staff1

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:

alerting:
  alertmanagers:
    - scheme: https
      basic_auth:
        password_file: /etc/prometheus/alertmanager.password
      static_configs:
        - targets:
            - alertmanager.bodkys.house
