---
global:
  external_labels:
    prom_instance: dbodky-staff1

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093
