---
global:
  external_labels:
    prom_instance: dbodky-staff1

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
