---
certbot:
  hosts:
    staff-dbodky1:
      certbot_certs:
        - domains:
            - portainer.bodkys.house
docker:
  hosts:
    staff-dbodky1: {}
    staff-dbodky2: {}
portainer:
  hosts:
    staff-dbodky1: {}
