---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: homepage-secrets
  data:
    - secretKey: pihole-api-key
      remoteRef:
        key: PIHOLE_API_KEY
