---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: managemeals-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # sync first
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: managemeals-secrets
  data:
    - secretKey: MANAGEMEALS_MONGO_URL
      remoteRef:
        key: MANAGEMEALS_MONGO_URL
    - secretKey: MANAGEMEALS_TYPESENSE_API_KEY
      remoteRef:
        key: MANAGEMEALS_TYPESENSE_API_KEY
    - secretKey: MANAGEMEALS_ACCESS_JWT_SECRET
      remoteRef:
        key: MANAGEMEALS_ACCESS_JWT_SECRET
    - secretKey: MANAGEMEALS_REFRESH_JWT_SECRET
      remoteRef:
        key: MANAGEMEALS_REFRESH_JWT_SECRET
    - secretKey: MANAGEMEALS_COOKIE_ACCESS_TOKEN
      remoteRef:
        key: MANAGEMEALS_COOKIE_ACCESS_TOKEN
    - secretKey: MANAGEMEALS_COOKIE_REFRESH_TOKEN
      remoteRef:
        key: MANAGEMEALS_COOKIE_REFRESH_TOKEN
    - secretKey: MANAGEMEALS_MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: MANAGEMEALS_MONGO_INITDB_ROOT_PASSWORD
