---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: rook-ceph
  project: infrastructure
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.13.5
    helm:
      values: |
        enableDiscoveryDaemon: true
  syncPolicy:
    #    automated:
    #      selfHeal: true
    syncOptions:
      - CreateNamespace=true
