---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: velero
  project: infrastructure
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 6.0.0
    helm:
      values: |
        configuration:
          backupStorageLocation:
            - name: rook
              provider: velero.io/aws
              bucket: velero-backup
              default: true
              config:
                s3ForcePathStyle: "true"
                s3Url: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
          defaultBackupStorageLocation: rook
        credentials:
          existingSecret: velero-backup
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
