---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: velero
  project: infrastructure
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 6.0.0
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          - name: velero-plugin-for-csi
            image: velero/velero-plugin-for-csi:v0.7.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
            - name: civo
              provider: velero.io/aws
              bucket: velero
              default: true
              config:
                region: "civo"
                s3ForcePathStyle: "true"
                s3Url: https://objectstore.fra1.civo.com
          defaultBackupStorageLocation: civo
          features: EnableCSI
        credentials:
          useSecret: false
          extraSecretRef: civo-s3-credentials
        snapshotsEnabled: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
