---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync first
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: infrastructure
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.1
    helm:
      releaseName: cert-manager
      valuesObject:
        installCRDs: true
        crds:
          enabled: true
          keep: true
        enableCertificateOwnerRef: true # delete secrets when certs get deleted
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
