---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  destination:
    name: in-cluster
    namespace: cnpg-system
  project: infrastructure
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.20.1
    helm:
      releaseName: cnpg
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
