---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync second
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: external-dns
  project: infrastructure
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.3
    helm:
      releaseName: external-dns
      valuesObject:
        env:
          - name: CIVO_TOKEN
            valueFrom:
              secretKeyRef:
                name: civo-token
                key: token
        sources:
          - ingress
        domain_filters:
          - bodkys.house
        provider:
          name: civo
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
