---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: infrastructure
  source:
    repoURL: https://github.com/mocdaniel/homelab.git
    path: gitops/manifests/infrastructure/external-snapshotter
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
