---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-secretstores
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync first
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: infrastructure
  source:
    repoURL: https://github.com/mocdaniel/homelab.git
    path: gitops/manifests/infrastructure/external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
