---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: infrastructure
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          ingressClassResource:
            default: true
          extraArgs:
            enable-ssl-passthrough: "true"
            default-ssl-certificate: "ingress-nginx/bodkys-house-wildcard"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
