---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3" # sync third
spec:
  destination:
    name: in-cluster
    namespace: velero
  project: infrastructure
  source:
    repoURL: https://github.com/mocdaniel/homelab.git
    path: gitops/manifests/infrastructure/velero
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
