---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-ghostfolio
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  storage:
    size: 8Gi
    storageClass: ceph-block-postgres
