---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
  labels:
    app.kubernetes.io/name: ghostfolio
  annotations:
    argocd.argoproj.io/sync-wave: "2" # sync second
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: ghostfolio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghostfolio
    spec:
      containers:
        - name: ghostfolio
          image: "ghcr.io/gethomepage/homepage:v0.8.8"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
