---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
  labels:
    app.kubernetes.io/name: ghostfolio
  annotations:
    argocd.argoproj.io/sync-wave: "3" # sync third
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: ghostfolio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghostfolio
    spec:
      containers:
        - name: ghostfolio
          image: ghostfolio/ghostfolio:2.66.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-credentials
                  key: uri
            - name: NODE_ENV
              value: production
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-credentials
                  key: password
            - name: REDIS_HOST
              value: ghostfolio-redis-0
            - name: ACCESS_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: access-token-salt
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-secrets
                  key: jwt-secret-key
