---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghostfolio-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: ghostfolio-secrets
  data:
    - secretKey: jwt-secret-key
      remoteRef:
        key: GHOSTFOLIO_JWT_SECRET_KEY
    - secretKey: access-token-salt
      remoteRef:
        key: GHOSTFOLIO_ACCESS_TOKEN_SALT
    - secretKey: redis-password
      remoteRef:
        key: GHOSTFOLIO_REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghostfolio-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1" # sync first
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: ghostfolio-credentials
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: GHOSTFOLIO_PG_USER
    - secretKey: password
      remoteRef:
        key: GHOSTFOLIO_PG_PASSWORD
