---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio-redis
  labels:
    app.kubernetes.io/name: ghostfolio-redis
spec:
  selector:
    app.kubernetes.io/name: ghostfolio-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio
  labels:
    app.kubernetes.io/name: ghostfolio
spec:
  type: ClusterIP
  ports:
    - port: 3333
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ghostfolio
