apiVersion: v1
kind: Service
metadata:
  name: ghostfolio-redis
  labels:
    app.kubernetes.io/name: ghostfolio-redis
spec:
  selector:
    app.kubernetes.io/name: ghostfolio-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
