version: '3'

services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.rule=Host(`traefik.bodkys.house`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=daniel:$$2y$$05$$KPgO1p2afBo4YvPkM.USauSYxEk2xKR9LG90k4I7KKanNbNYESGwS"
      - "traefik.http.middlewares.redirectHTTPS.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirectHTTPS.redirectscheme.permanent=true"
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/traefik/acme:/etc/traefik/acme
    networks:
      - traefik

networks:
  traefik:
    external: true
