---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: infrastructure
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.3
    helm:
      values: |
        installCRDs: true
        # crds:
        #   enabled: true
        #   keep: true
        # enableCertificateOwnerRef: true  # delete secrets when certs get deleted
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
