---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dbodky@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          webhook:
            solverName: "civo"
            groupName: civo.webhook.okteto.com
            config:
              secretName: civo-token
              secretKey: token
