---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-star-bodkys-house
  namespace: cert-manager
spec:
  commonName: "*.bodkys.house"
  dnsNames:
    - "*.bodkys.house"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: staging-star-bodkys-house
