---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-auth-token
            namespace: kube-system
            key: token
