---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civo-token
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: civo-token
  data:
    - secretKey: token
      remoteRef:
        key: CIVO_TOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civo-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: civo-token
  data:
    - secretKey: token
      remoteRef:
        key: CIVO_TOKEN
